apiVersion: v1
kind: Pod
metadata:
  name: cuda-eesposit
spec:
  restartPolicy: Never
  containers:
    - name: cuda-eesposit
      image: "quay.io/eesposit/gpu-test:latest"
      command:
        - sleep
      args:
        - infinity
      resources:
        limits:
          nvidia.com/gpu: 1
      nodeSelector:
        nvidia.com/gpu.present: true
